spring:
    application:
        name: mina
    
    datasource:
        url: jdbc:mysql://localhost:3306?databaseName=mydb
        username: root
        password: dnsgkdtlf11
        driver-class-name: com.mysql.jdbc.Driver

    server:
        port: 8080
        servlet:
            context-path: /mina