spring:
    application:
        name: mina
    
    datasource:
        url: jdbc:sqlserver://43.200.45.240:1433?databaseName=mina
        username: sa
        password: mina123!
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    server:
        port: 8080
        servlet:
            context-path: /mina