spring:
    application:
        name: mina
    # DB 설정
    datasource:
        url: jdbc:sqlserver://43.200.45.240:1433?databaseName=mina
        username: sa
        password: mina123!
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# AWS S3 설정
cloud:
    aws:
        s3:
            bucket: mina-file-server
        region:
            static: ap-northeast-2
        credentials:
            access-key: ${AWS_ACCESS_KEY_ID} 
            secret-key: ${AWS_SECRET_ACCESS_KEY}

# 서버 설정
server:
    port: 8080
    servlet:
        context-path: /mina

# MyBatis 설정
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.tuk.mina


# 로깅            
logging:
    level:
        org.springframework.security: DEBUG