name: deploy mina api-server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh ec2 접속
        uses: appleboy/ssh-action@v1
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script-stop: true
          script: |
            cd /home/ubuntu/api-server
            rm -rf /src/main/resources/application.yml
            git pull origin main
            chmod +x mvnw
            echo $APPLICATION_PROPERTIES > src/main/resources/application.yml
            ./mvnw clean package
            # 서버가 안돌가고 있으면 fuser 명령어가 실패하므로 || true 로 무시
            sudo fuser -k 8080 || true
            # 표준출력
            nohup java -jar target/*SNAPSHOT.jar > ./output.log 2>&1 & 
            